---
# Project info
name:                           PandemicSAS
author:                         Ian Riley, grad

#==============================================================================#
### COLOR CONF - BEGIN ###

# The allowable color types - each color type must be a String
colors:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
    -                           White

### COLOR CONF - END ###
#==============================================================================#

#==============================================================================#
### DISEASE CONF - BEGIN ###

# Disease types - type must be in '#colors'
diseases:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

# Curable Disease types - type must be in '#diseases'
curable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

# Eradicable Disease types - type must be in '#diseases'
eradicable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

### DISEASE CONF - END ###
#==============================================================================#

#==============================================================================#
### CITY CONF - BEGIN ###

# City locations - each city must have a 'name' and a 'color'
# 'name' must be a String
# 'color' must be in '#colors'
cities:
    - name:                     Los Angeles
      color:                    Yellow
    - name:                     Mexico City
      color:                    Yellow
    - name:                     Miami
      color:                    Yellow
    - name:                     Bogota
      color:                    Yellow
    - name:                     Lima
      color:                    Yellow
    - name:                     Santiago
      color:                    Yellow
    - name:                     Buenos Aires
      color:                    Yellow
    - name:                     Sao Paulo
      color:                    Yellow
    - name:                     Lagos
      color:                    Yellow
    - name:                     Kinshasa
      color:                    Yellow
    - name:                     Johannesburg
      color:                    Yellow
    - name:                     Khartoum
      color:                    Yellow
    - name:                     Beijing
      color:                    Red
    - name:                     Seoul
      color:                    Red
    - name:                     Tokyo
      color:                    Red
    - name:                     Shanghai
      color:                    Red
    - name:                     Bangkok
      color:                    Red
    - name:                     Hong Kong
      color:                    Red
    - name:                     Taipei
      color:                    Red
    - name:                     Osaka
      color:                    Red
    - name:                     Jakarta
      color:                    Red
    - name:                     Ho Chi Minh City
      color:                    Red
    - name:                     Manila
      color:                    Red
    - name:                     Sydney
      color:                    Red
    - name:                     San Francisco
      color:                    Blue
    - name:                     Chicago
      color:                    Blue
    - name:                     Atlanta
      color:                    Blue
    - name:                     Montreal
      color:                    Blue
    - name:                     Washington
      color:                    Blue
    - name:                     New York
      color:                    Blue
    - name:                     Madrid
      color:                    Blue
    - name:                     London
      color:                    Blue
    - name:                     Paris
      color:                    Blue
    - name:                     Essen
      color:                    Blue
    - name:                     Milan
      color:                    Blue
    - name:                     St. Petersburg
      color:                    Blue
    - name:                     Algiers
      color:                    Black
    - name:                     Istanbul
      color:                    Black
    - name:                     Cairo
      color:                    Black
    - name:                     Moscow
      color:                    Black
    - name:                     Baghdad
      color:                    Black
    - name:                     Tehran
      color:                    Black
    - name:                     Karachi
      color:                    Black
    - name:                     Riyadh
      color:                    Black
    - name:                     Mumbai
      color:                    Black
    - name:                     Delhi
      color:                    Black
    - name:                     Kolkata
      color:                    Black
    - name:                     Chennai
      color:                    Black

### CITY CONF - END ###
#==============================================================================#

#==============================================================================#
### OUTBREAKS CONF - BEGIN ###

# The maximum allowable number of outbreaks before game loss
# must be a positive Integer
max_outbreaks:                  7

# The initial number of outbreaks that have occurred
# must be a non-negative Integer <= '#max_outbreaks'
init_outbreaks:                 0

### OUTBREAKS CONF - END ###
#==============================================================================#

#==============================================================================#
### RESEARCH STATIONS CONF - BEGIN ###

# Research Station location - each location must be a 'name' in '#cities'
research_stations:
    -                           Atlanta

### RESEARCH STATIONS CONF - END ###
#==============================================================================#

#==============================================================================#
### ROLES CONF - BEGIN ###

# The allowable roles for a pawn
roles:
    -                           None
    -                           Random
    -                           Contingency Planner
    -                           Dispatcher
    -                           Medic
    -                           Operations Expert
    -                           Quarantine Specialist
    -                           Researcher
    -                           Scientist

### ROLES CONF - END ###
#==============================================================================#

#==============================================================================#
### PAWNS CONF - BEGIN ###

# The maximum number of pawns that can be placed on the board
# must be a positive Integer
max_pawns:                      4

# The initial number of pawns to place on the board
# must be a non-negative Integer <= '#max_pawns'
init_pawns:                     2

# The start location for each pawn
# each location must be a location in '#research_stations'
# must be same size as '#max_pawns'
pawn_init_locations:
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta

# The initial role for each pawn - each role must be a role in '#roles'
# must be the same size as '#max_pawns'
pawn_init_roles:
    -                           None
    -                           None
    -                           None
    -                           None

### PAWNS CONF - END ###
#==============================================================================#

#==============================================================================#
### HAND SIZE CONF - BEGIN ###

# The maximum number of cards that any pawn can have in hand at end-of-turn
# must be a positive Integer
max_hand_size:                  7

# The starting hand size of each pawn according to '#num_pawns'
# must be the same size as '#max_pawns'
# each hand size must be a non-negative Integer <= '#max_hand_size'
init_hand_size:
    -                           4
    -                           4
    -                           3
    -                           2

### HAND SIZE CONF - END ###
#==============================================================================#

#==============================================================================#
### SECTION CONF - BEGIN ###

### SECTION CONF - END ###
#==============================================================================#

...
