---
# Project info
name:                           PandemicSAS
author:                         Ian Riley, grad

#==============================================================================#
### COLOR CONF - BEGIN ###

# The allowable color types - each color type must be a String
colors:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
    -                           Green
    -                           Gold

### COLOR CONF - END ###
#==============================================================================#

#==============================================================================#
### DISEASE CONF - BEGIN ###

# Disease types - type must be in '#colors'
diseases:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

# Curable disease types - type must be in '#diseases'
curable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

# The number of diseases that must be cured to win the game
# must be a positive Integer
# cannot be larger than the size of '#curable'
max_diseases_cured:             1

# The diseases that are initially cured
# each type must be none or be in '#curable'
init_diseases_cured:
    -                           none

# Eradicable disease types - type must be in '#diseases'
eradicable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black

# The number of diseases that must be eradicated to win the game
# must be a positive Integer
# cannot be larger than the size of '#eradicable'
max_diseases_eradicated:        0

# The diseases that are initially eradicated
# each type must be none or be in '#eradicable'
init_diseases_eradicated:
    -                           none

# The maximum number of disease cubes for any disease type
# must be a positive Integer
max_disease_cubes:              24

# The minimum number of disease cubes for any disease type
# must be a non-negative Integer
min_disease_cubes:              0

# The number of disease cubes for each disease type
# must have 'color' and 'count'
# each 'color' must be in '#diseases'
# must have each type in '#diseases'
# each 'count' must be a non-negative Integer
# '#min_disease_cubes' <= 'count' <= '#max_disease_cubes'
disease_cubes:
    - color:                    Yellow
      count:                    24
    - color:                    Red
      count:                    24
    - color:                    Blue
      count:                    24
    - color:                    Black
      count:                    24

### DISEASE CONF - END ###
#==============================================================================#

#==============================================================================#
### CITY CONF - BEGIN ###

# City locations - each city must have a 'name' and a 'color'
# 'name' must be a String
# 'color' must be in '#colors'
cities:
    - name:                     Los Angeles
      color:                    Yellow
    - name:                     Mexico City
      color:                    Yellow
    - name:                     Miami
      color:                    Yellow
    - name:                     Bogota
      color:                    Yellow
    - name:                     Lima
      color:                    Yellow
    - name:                     Santiago
      color:                    Yellow
    - name:                     Buenos Aires
      color:                    Yellow
    - name:                     Sao Paulo
      color:                    Yellow
    - name:                     Lagos
      color:                    Yellow
    - name:                     Kinshasa
      color:                    Yellow
    - name:                     Johannesburg
      color:                    Yellow
    - name:                     Khartoum
      color:                    Yellow
    - name:                     Beijing
      color:                    Red
    - name:                     Seoul
      color:                    Red
    - name:                     Tokyo
      color:                    Red
    - name:                     Shanghai
      color:                    Red
    - name:                     Bangkok
      color:                    Red
    - name:                     Hong Kong
      color:                    Red
    - name:                     Taipei
      color:                    Red
    - name:                     Osaka
      color:                    Red
    - name:                     Jakarta
      color:                    Red
    - name:                     Ho Chi Minh City
      color:                    Red
    - name:                     Manila
      color:                    Red
    - name:                     Sydney
      color:                    Red
    - name:                     San Francisco
      color:                    Blue
    - name:                     Chicago
      color:                    Blue
    - name:                     Atlanta
      color:                    Blue
    - name:                     Montreal
      color:                    Blue
    - name:                     Washington
      color:                    Blue
    - name:                     New York
      color:                    Blue
    - name:                     Madrid
      color:                    Blue
    - name:                     London
      color:                    Blue
    - name:                     Paris
      color:                    Blue
    - name:                     Essen
      color:                    Blue
    - name:                     Milan
      color:                    Blue
    - name:                     St. Petersburg
      color:                    Blue
    - name:                     Algiers
      color:                    Black
    - name:                     Istanbul
      color:                    Black
    - name:                     Cairo
      color:                    Black
    - name:                     Moscow
      color:                    Black
    - name:                     Baghdad
      color:                    Black
    - name:                     Tehran
      color:                    Black
    - name:                     Karachi
      color:                    Black
    - name:                     Riyadh
      color:                    Black
    - name:                     Mumbai
      color:                    Black
    - name:                     Delhi
      color:                    Black
    - name:                     Kolkata
      color:                    Black
    - name:                     Chennai
      color:                    Black

### CITY CONF - END ###
#==============================================================================#

#==============================================================================#
### OUTBREAKS CONF - BEGIN ###

# The maximum allowable number of outbreaks before game loss
# must be a positive Integer
max_outbreaks:                  7

# The initial number of outbreaks that have occurred
# must be a non-negative Integer <= '#max_outbreaks'
init_outbreaks:                 0

### OUTBREAKS CONF - END ###
#==============================================================================#

#==============================================================================#
### INFECTION RATE - BEGIN ###

# The maximum number of infection rate intensities
# must be a positive Integer
max_infection_rates:            7

# The initial rate from which to choose the infection rate intensity
# must be a positive Integer <= '#max_infection_rates'
init_infection_rate:            1

# The maximum intensity for any infection rate
# must be a positive Integer
max_infection_rate:             4

# The infection rate intensities
# must be the same size as '#max_infection_rates'
# each intensity must be a positive Integer <= '#max_infection_rate'
infection_rates:
    -                           2
    -                           2
    -                           2
    -                           3
    -                           3
    -                           4
    -                           4

### INFECTION RATE - END ###
#==============================================================================#

#==============================================================================#
### RESEARCH STATIONS CONF - BEGIN ###

# The maximum number of research statations that can be on the board
# must be a positive Integer
max_research_stations:          6

# Research station location - each location must be a 'name' in '#cities'
# must be at least 1, but no more than '#max_research_stations'
research_stations:
    -                           Atlanta

### RESEARCH STATIONS CONF - END ###
#==============================================================================#

#==============================================================================#
### ROLES CONF - BEGIN ###

# The allowable roles for a pawn
roles:
    -                           None
    -                           Random
    -                           Contingency Planner
    -                           Dispatcher
    -                           Medic
    -                           Operations Expert
    -                           Quarantine Specialist
    -                           Researcher
    -                           Scientist

# Whether each role can only be assigned to one pawn
roles_are_unique:               false

### ROLES CONF - END ###
#==============================================================================#

#==============================================================================#
### PAWNS CONF - BEGIN ###

# The maximum number of pawns that can be placed on the board
# must be a positive Integer
max_pawns:                      4

# The initial number of pawns to place on the board
# must be a positive Integer <= '#max_pawns'
init_pawns:                     2

# The start location for each pawn
# each location must be a location in '#research_stations'
# must be same size as '#max_pawns'
pawn_init_locations:
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta

# The initial role for each pawn - each role must be a role in '#roles'
# must be the same size as '#max_pawns'
# each role must be unique if '#roles_are_unique'
pawn_init_roles:
    -                           None
    -                           None
    -                           None
    -                           None

### PAWNS CONF - END ###
#==============================================================================#

#==============================================================================#
### HAND SIZE CONF - BEGIN ###

# The maximum number of cards that any pawn can have in hand at end-of-turn
# must be a positive Integer
max_hand_size:                  7

# The starting hand size of each pawn according to '#num_pawns'
# must be the same size as '#max_pawns'
# each hand size must be a non-negative Integer <= '#max_hand_size'
init_hand_size:
    -                           4
    -                           4
    -                           3
    -                           2

### HAND SIZE CONF - END ###
#==============================================================================#

#==============================================================================#
### EVENTS CONF - BEGIN ###

# The names of the event cards - each name should be a String
events:
    -                           Airlift
    -                           Forecast
    -                           Government Grant
    -                           One Quiet Night
    -                           Resilient Population

### EVENTS CONF - END ###
#==============================================================================#

#==============================================================================#
### PLAYER DECK CONF - BEGIN ###

# The template to generate city cards for the player deck
# card templates should have a 'selector', a 'name', a 'color'
# 'selector' should be none for single or 'for $<id> in #<id>' for collection
# '$<id>' is a variable and '#<id>' is a collection
# 'name' should be a 'name' from '#cities', Any, or '$<id>.<prop>'
# 'color' should be a String from '#colors', Any, or '$<id>.<prop>'
city_card_template:
    - selector:                 for '$city' in '#cities'
      name:                     Any
      color:                    '$city.color'

# The template to generate event cards for the player deck
# card templates should have a 'selector', a 'name', a 'color'
# 'selector' should be none for single or 'for $<id> in #<id>' for collection
# '$<id>' is a variable and '#<id>' is a collection
# 'name' should be a 'name' from '#events', Any, or '$<id>.<prop>'
# 'color' should be a String from '#colors', Any, or '$<id>.<prop>'
event_card_template:
    - selector:                 for '$event' in '#events'
      name:                     '$event'
      color:                    Gold

# The template to generate epidemic cards for the player deck
# card templates should have a 'selector', a 'name', a 'color'
# 'selector' should be none for single or 'for $<id> in #<id>' for collection
# '$<id>' is a variable and '#<id>' is a collection
# 'name' should be Epidemic
# 'color' should be Green
epidemic_card_template:
    - selector:                 none
      name:                     Epidemic
      color:                    Green

# The template to generate blank cards for the player deck
# card templates should have a 'selector', a 'name', a 'color'
# 'selector' should be none for single or 'for $<id> in #<id>' for collection
# '$<id>' is a variable and '#<id>' is a collection
# 'name' should be none
# 'color' should be none
blank_card_template:
    - selector:                 none
      name:                     none
      color:                    none

# The template to generate the player deck
# each field should specity a template from config
# set the field to 'false' to not use the template
# set the field to 'true' to use the template once
# set the field to 0 to not use the template
# set the field to x to use the template x times
# note that 'selector' none is used to create a single card
player_deck_template:
    - city_card_template:       true
      event_card_template:      false
      epidemic_card_template:   4
      blank_card_template:      8

# The shuffle type to use to distribute init player cards
# must be riffle or pile
player_deck_shuffle_init:       riffle

# The shuffle type to use to distribute player cards during play
# must be riffle or pile
player_deck_shuffle:            pile

# The minimum number of cards in the deck before it is considered empty
# must be a non-negative Integer
min_player_deck_size:           0

# The action to take once the player deck is considered empty
# must be none, riffle, or pile
player_deck_empty_do:           none

### PLAYER DECK CONF - END ###
#==============================================================================#

#==============================================================================#
### INFECT DECK CONF - BEGIN ###

# The template to generate infect cards for the infect deck
# card templates should have a 'selector', a 'name', a 'color'
# 'selector' should be none for single or 'for $<id> in #<id>' for collection
# '$<id>' is a variable and '#<id>' is a collection
# 'name' should be a 'name' from '#cities', Any, or '$<id>.<prop>'
# 'color' should be Green
infect_card_template:
    - selector:                 for '$city' in '#cities'
      name:                     '$city.name'
      color:                    Green

# The template to generate the infect deck
# each field should specity a template from config
# set the field to 'false' to not use the template
# set the field to 'true' to use the template once
# set the field to 0 to not use the template
# set the field to x to use the template x times
# note that 'selector' none is used to create a single card
infect_deck_template:
    - infect_card_template:     true

# The shuffle type to use to distribute infect cards
# must be riffle or pile
infect_deck_shuffle:            riffle

# The minimum number of cards in the deck before it is considered empty
min_infect_deck_size:           0

# The action to take once the infect deck is considered empty
# must be none, riffle, or pile
infect_deck_empty_do:           riffle

### INFECT DECK CONF - END ###
#==============================================================================#

#==============================================================================#
### SECTION CONF - BEGIN ###

### SECTION CONF - END ###
#==============================================================================#

...
