# Project info
name:                           PandemicSAS
author:                         Ian Riley, grad
# Allowable color types
colors:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
    -                           White
# Disease types - type must be in '#colors'
diseases:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
# Curable Disease types - type must be in '#diseases'
curable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
# Eradicable Disease types - type must be in '#diseases'
eradicable:
    -                           Yellow
    -                           Red
    -                           Blue
    -                           Black
# City locations - each city must have a 'name' and a 'color' and 'color' must be in '#colors'
cities:
    - name:                     Los Angeles
      color:                    Yellow
    - name:                     Mexico City
      color:                    Yellow
    - name:                     Miami
      color:                    Yellow
    - name:                     Bogota
      color:                    Yellow
    - name:                     Lima
      color:                    Yellow
    - name:                     Santiago
      color:                    Yellow
    - name:                     Buenos Aires
      color:                    Yellow
    - name:                     Sao Paulo
      color:                    Yellow
    - name:                     Lagos
      color:                    Yellow
    - name:                     Kinshasa
      color:                    Yellow
    - name:                     Johannesburg
      color:                    Yellow
    - name:                     Khartoum
      color:                    Yellow
    - name:                     Beijing
      color:                    Red
    - name:                     Seoul
      color:                    Red
    - name:                     Tokyo
      color:                    Red
    - name:                     Shanghai
      color:                    Red
    - name:                     Bangkok
      color:                    Red
    - name:                     Hong Kong
      color:                    Red
    - name:                     Taipei
      color:                    Red
    - name:                     Osaka
      color:                    Red
    - name:                     Jakarta
      color:                    Red
    - name:                     Ho Chi Minh City
      color:                    Red
    - name:                     Manila
      color:                    Red
    - name:                     Sydney
      color:                    Red
    - name:                     San Francisco
      color:                    Blue
    - name:                     Chicago
      color:                    Blue
    - name:                     Atlanta
      color:                    Blue
    - name:                     Montreal
      color:                    Blue
    - name:                     Washington
      color:                    Blue
    - name:                     New York
      color:                    Blue
    - name:                     Madrid
      color:                    Blue
    - name:                     London
      color:                    Blue
    - name:                     Paris
      color:                    Blue
    - name:                     Essen
      color:                    Blue
    - name:                     Milan
      color:                    Blue
    - name:                     St. Petersburg
      color:                    Blue
    - name:                     Algiers
      color:                    Black
    - name:                     Istanbul
      color:                    Black
    - name:                     Cairo
      color:                    Black
    - name:                     Moscow
      color:                    Black
    - name:                     Baghdad
      color:                    Black
    - name:                     Tehran
      color:                    Black
    - name:                     Karachi
      color:                    Black
    - name:                     Riyadh
      color:                    Black
    - name:                     Mumbai
      color:                    Black
    - name:                     Delhi
      color:                    Black
    - name:                     Kolkata
      color:                    Black
    - name:                     Chennai
      color:                    Black
# Research Station location - each location must be a 'name' in '#cities'
research_stations:
    -                           Atlanta
# The maximum number of pawns that can be placed on the board - must be greater than 0
max_pawns:                      4
# The number of pawns to place on the board - can't be more pawns than '#max_pawns'
num_pawns:                      2
# The start location for each pawn - each location must be a location in '#research_stations'
# must be same size as '#max_pawns'
pawn_start_locations:
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta
    -                           Atlanta
# The starting hand size of each pawn according to '#num_pawns'
# must be the same size as '#max_pawns'
starting_hand_size:
    -                           4
    -                           4
    -                           3
    -                           2
